sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        package:
          - clang-3.8
      env:
        MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - os: linux
      addons:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        package:
          - g++-7
      env:
        MATRIX_EVAL="CC gcc-7 && CXX=g++-7"
script:
  - cmake .
  - make