sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        package:
          - clang-3.8
      env:
        COMPILER=clang++-3.8
    - os: linux
      addons:
        sources:
          - ubuntu-toolchain-r-test
        package:
          - g++-7
      env:
        COMPILER=g++-7

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - make